/**
 * Codigos de mercancia (MERCANCIAREMESA) mas usados en el transporte de carga
 * por carretera en Colombia: capitulo + partida del Sistema Armonizado, que es
 * lo que pide la remesa [REM pag. 15]. Se guardan con dos ceros a la izquierda
 * (4707 -> 004707).
 *
 * Es una lista para elegir rapido, no el maestro completo del RNDC: cualquier
 * otro codigo se puede escribir a mano en la plantilla. Si el RNDC no lo
 * reconoce, lo dira al enviar la remesa.
 */
export const MERCANCIAS_COMUNES: Record<string, string> = {
  // Animales, alimentos y agro
  "0102": "Animales vivos de la especie bovina (ganado)",
  "0103": "Animales vivos de la especie porcina",
  "0201": "Carne de bovino fresca o refrigerada",
  "0203": "Carne de porcino fresca, refrigerada o congelada",
  "0207": "Carne y despojos de aves (pollo)",
  "0303": "Pescado congelado",
  "0401": "Leche y nata (crema) sin concentrar",
  "0407": "Huevos de ave con cascara",
  "0603": "Flores y capullos cortados",
  "0701": "Papas frescas o refrigeradas",
  "0702": "Tomates frescos o refrigerados",
  "0703": "Cebollas, ajos y puerros",
  "0709": "Las demas hortalizas frescas o refrigeradas",
  "0714": "Yuca, name y raices similares",
  "0803": "Bananos y platanos",
  "0804": "Datiles, higos, pinas, aguacates, mangos",
  "0805": "Agrios (citricos) frescos o secos",
  "0810": "Las demas frutas frescas",
  "0901": "Cafe",
  "1001": "Trigo",
  "1005": "Maiz",
  "1006": "Arroz",
  "1101": "Harina de trigo",
  "1201": "Habas (porotos) de soya",
  "1507": "Aceite de soya",
  "1511": "Aceite de palma",
  "1701": "Azucar de cana o remolacha",
  "1704": "Confiteria sin cacao",
  "1806": "Chocolate y preparaciones con cacao",
  "1902": "Pastas alimenticias",
  "1905": "Productos de panaderia y galleteria",
  "2005": "Hortalizas preparadas o en conserva",
  "2009": "Jugos de frutas u hortalizas",
  "2106": "Preparaciones alimenticias diversas",
  "2201": "Agua mineral y gaseada",
  "2202": "Bebidas no alcoholicas (gaseosas, refrescos)",
  "2203": "Cerveza de malta",
  "2208": "Aguardientes, licores y demas bebidas espirituosas",
  "2304": "Torta de soya y demas residuos solidos",
  "2309": "Preparaciones para alimentacion de animales (concentrados)",

  // Minerales, construccion y combustibles
  "2501": "Sal",
  "2505": "Arenas naturales",
  "2517": "Cantos, grava, piedras machacadas",
  "2520": "Yeso",
  "2521": "Piedra caliza",
  "2522": "Cal",
  "2523": "Cemento",
  "2701": "Hullas (carbon mineral)",
  "2704": "Coques y semicoques de hulla",
  "2710": "Aceites de petroleo (combustibles, lubricantes)",
  "2711": "Gas de petroleo (GLP)",
  "2713": "Coque de petroleo y betun",
  "2715": "Mezclas bituminosas (asfalto)",

  // Quimicos y plasticos
  "2815": "Hidroxido de sodio (soda caustica)",
  "2836": "Carbonatos (carbonato de calcio, de sodio)",
  "3102": "Abonos minerales o quimicos nitrogenados",
  "3105": "Abonos minerales o quimicos (NPK)",
  "3208": "Pinturas y barnices",
  "3209": "Pinturas y barnices en medio acuoso",
  "3401": "Jabon",
  "3402": "Detergentes y preparaciones para lavar",
  "3808": "Insecticidas, fungicidas, herbicidas",
  "3901": "Polimeros de etileno en formas primarias",
  "3902": "Polimeros de propileno en formas primarias",
  "3904": "Policloruro de vinilo (PVC) en formas primarias",
  "3915": "Desechos, desperdicios y recortes de plastico",
  "3917": "Tubos y accesorios de plastico",
  "3920": "Placas, laminas y peliculas de plastico",
  "3923": "Envases y articulos de plastico para transporte",
  "4011": "Neumaticos (llantas) nuevos de caucho",
  "4012": "Neumaticos recauchutados o usados",

  // Madera, papel y carton
  "4401": "Lena, madera en plaquitas o particulas",
  "4403": "Madera en bruto",
  "4407": "Madera aserrada",
  "4410": "Tableros de particulas",
  "4411": "Tableros de fibra de madera (MDF)",
  "4412": "Madera contrachapada",
  "4415": "Estibas, cajones y embalajes de madera",
  "4707": "Papel o carton para reciclar (desperdicios y desechos)",
  "4802": "Papel y carton sin estucar para escribir o imprimir",
  "4804": "Papel y carton Kraft sin estucar, en bobinas u hojas",
  "4805": "Los demas papeles y cartones sin estucar, en bobinas u hojas",
  "4808": "Papel y carton corrugados, rizados o plisados",
  "4810": "Papel y carton estucados",
  "4818": "Papel higienico, servilletas, panuelos y similares",
  "4819": "Cajas, sacos y envases de papel o carton",

  // Textiles
  "5201": "Algodon sin cardar ni peinar",
  "6305": "Sacos y talegas para envasar",

  // Construccion, ceramica y vidrio
  "6802": "Piedras de talla o construccion trabajadas (marmol)",
  "6807": "Manufacturas de asfalto (tejas, mantos)",
  "6809": "Manufacturas de yeso (drywall)",
  "6810": "Manufacturas de cemento u hormigon (bloques, tubos)",
  "6811": "Manufacturas de fibrocemento (tejas)",
  "6904": "Ladrillos de ceramica",
  "6905": "Tejas de ceramica",
  "6907": "Baldosas y placas de ceramica",
  "6910": "Fregaderos, lavabos e inodoros de ceramica",
  "7005": "Vidrio flotado en hojas",
  "7010": "Botellas, frascos y envases de vidrio",

  // Metales
  "7204": "Desperdicios y desechos de hierro o acero (chatarra)",
  "7208": "Laminados planos de hierro o acero en caliente",
  "7210": "Laminados planos de hierro o acero chapados o revestidos",
  "7213": "Alambron de hierro o acero",
  "7214": "Barras de hierro o acero (varilla corrugada)",
  "7216": "Perfiles de hierro o acero",
  "7306": "Tubos de hierro o acero",
  "7308": "Construcciones y partes de hierro o acero",
  "7312": "Cables de hierro o acero",
  "7403": "Cobre refinado",
  "7602": "Desperdicios y desechos de aluminio",
  "7604": "Barras y perfiles de aluminio",

  // Maquinaria, vehiculos y muebles
  "8418": "Refrigeradores y congeladores",
  "8429": "Maquinaria de movimiento de tierras",
  "8450": "Lavadoras de ropa",
  "8701": "Tractores",
  "8703": "Automoviles de turismo",
  "8704": "Vehiculos para transporte de mercancias",
  "8716": "Remolques y semirremolques",
  "9401": "Asientos",
  "9403": "Muebles y sus partes",
};
